# fly.toml app configuration file generated for ...
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrape-site'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
